version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout fire
     - run: docker build . -t ci
     - run: docker run -it -e TELEGRAM_TOKEN=${TELEGRAM_TOKEN} -e PULL_REQUEST_NUMBER=${PULL_REQUEST_NUMBER} -e GH_PERSONAL_TOKEN=${GH_PERSONAL_TOKEN} ci
